source 'https://rubygems.org'

gem 'sinatra'
gem 'sass'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'mysql'
gem 'pry', '0.10.1'
gem 'pry-byebug'
gem 'sinatra-flash'
gem 'json'
gem 'grape'
gem 'grape-entity'